# 禁止倒卖 汉化作者 INSide_734
# QQ: 3217962725
name: MMOItems
version: 6.9.5-SNAPSHOT
main: net.Indyuce.mmoitems.MMOItems
author: Indyuce
description: A great item solution for your RPG server!!
depend: [MythicLib]
softdepend: [WorldGuard,Residence,BossShopPro,SkillAPI,SkillsPro,MMOCore,MMOProfiles,MythicMobs,MMOInventory,PlaceholderAPI,Vault,Denizen,AureliumSkills]
api-version: 1.13
commands:
    mmoitems:
        description: MMOItems主命令。
        aliases: [mi]
    updateitem:
        description: 更新手持物品。
        aliases: [upitem, itemup]
        permission: mmoitems.update

permissions:
    mmoitems.admin:
        description: 访问管理员命令。
        default: op
    mmoitems.update:
        description: 访问 /updateitem 命令。
        default: op
    mmoitems.edit.op:
        description: 允许编辑 op 属性，如 commands。
        default: false
    mmoitems.bypass.item:
        description: 绕过物品权限限制。
        default: false
    mmoitems.bypass.ability:
        description: 绕过技能权限限制。
        default: false
    mmoitems.bypass.class:
        description: 绕过物品类别限制。
        default: false
    mmoitems.bypass.soulbound:
        description: 绕过绑定限制。
        default: false
    mmoitems.bypass.level:
        description: 绕过物品等级限制。
        default: false
    mmoitems.update-notify:
        description: 接收新版本更新时的通知。
        default: op
    mmoitems.soulbound:
        description: 允许使用 /soulbound 命令。
        default: op